### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Toni-d-e-v** [DRok17/RetroBuilder-3.0-N64#1]
Im trying to build it and nothing happen it says please wait and it closes the program, and says it cant find data but I put everything in input folder!
![image](https://user-images.githubusercontent.com/62844491/116527510-07f91280-a8db-11eb-8762-799f762ec940.png)

**Comment by Toni-d-e-v** [comment]
@DRok17  im on win 7 also i got some vc error for some tool called pgcout somthin like that

**Comment by Toni-d-e-v** [comment]
![image](https://user-images.githubusercontent.com/62844491/116527841-658d5f00-a8db-11eb-9cbe-aea711b1dc73.png)

**Comment by DRok17** [comment]
For the data missing error, seems like you don't have an icon0.png file. That might be the cause.

As for the VC error, please see link below as this is an known issue:

https://github.com/kornelski/pngquant/issues/253

**Comment by Toni-d-e-v** [comment]
@DRok17 Its okay i made it. Thanks anyways
