### ISSUE TITLE
The VPK is not generated in VPK folder

### ISSUE THREAD

**Issue by andikahakim17** [DRok17/RetroBuilder-3.0-N64#5]
hi @DRok17  I already executed the step properly but the VPK is not generated in the VPK folder, I'm using Win 10 and also no error message pop up

**Comment by DRok17** [comment]
Game name and system type please.

Also, are all bg, icon0 and startup pngs in the content folder at the time of generating?

**Comment by andikahakim17** [comment]
Hi Thanks for your response, it's Mega Man Nes, yeah all the files are in the folder, I attached the process
Regards,

![VB1](https://user-images.githubusercontent.com/41132905/134438423-eb78bd22-05fa-4457-a879-3d87d9c82053.png)
![VB2](https://user-images.githubusercontent.com/41132905/134438422-4dabf5e3-48c8-480f-906c-28d51f772775.png)
![VB3](https://user-images.githubusercontent.com/41132905/134438421-73026111-1950-426e-bba3-9036c9934280.png)
![VB4](https://user-images.githubusercontent.com/41132905/134438420-69302ff8-ec3c-47b1-925e-b255a8e2c04e.png)
![VB5](https://user-images.githubusercontent.com/41132905/134438418-f62b69b3-b185-44dc-8dbc-caed7ec8b952.png)
![VB6](https://user-images.githubusercontent.com/41132905/134438415-80ce0c54-099b-4431-a58c-11d195cf6641.png)
![VB7](https://user-images.githubusercontent.com/41132905/134438413-36b62f2a-8ce2-4b11-80ef-6890473c4f20.png)

**Comment by DRok17** [comment]
Hm, I can't see anything wrong, though I would like the see the "Contents" folder, it's possible one of those PNGs got deleted by the process (sometimes it can be finicky).

Do the Rom.txt and Core.txt files generate correctly?

I've actually moved on to this project which uses a modified version of RetroBuilder, it might work better for you:

https://github.com/DRok17/Multi-Builder

**Comment by andikahakim17** [comment]
Hi, I'm using another laptop with windows OS and it succeed.
Still I failed using VM, anyway I will close this issue

**Comment by DRok17** [comment]
Thanks for letting me know it works via Windows 10 natively. I haven't tested this on a VM before, so it could be related to that setup.
