### ISSUE TITLE
Restart required to switch between bubbles

### ISSUE THREAD

**Issue by dantesquivel** [DRok17/RetroBuilder-3.0-N64#8]
I have succesfully created several bubbles for GB[C/A] games with Retroarch and N64 with Daedalus, however, if I close out of one bubble and try to open up another it just goes back and forth to the live area for the game, without ever launching the emulator (either retroarch or daedalus) I have to reboot the device any time I need to switch between bubbles

**Comment by DRok17** [comment]
This has been brought up a couple of times, not much I can do about it as it relates to the eboot itself. Closing RA or DX64 may resolve it.
